instagram/instagram/Controllers/PostController.cs
using instagram.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace instagram.Controllers
{
    public class PostController : Controller
    {
        private instagramdb db = new instagramdb();

        // GET: Post
        public ActionResult Create()
        {
            if(Session["Iduser"] == "0" || Session["Iduser"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase photo)
        {
            int x = Convert.ToInt32(Session["Iduser"]);
            userinfo User = db.userinfos.Find(x);
            Post post = new Post();
            
            try
            {
                
                if (photo != null)
                {
                    string _FileName = Path.GetFileName(photo.FileName);
                    string _path = Path.Combine(Server.MapPath("~/photos"), _FileName);
                    photo.SaveAs(_path);
                    post.photo = "/PostPhoto/" + _FileName;
                    post.Userinfo = User;
                }
                db.posts.Add(post);
                db.SaveChanges();
            }
            catch
            {
                ViewBag.Ex = "";
                return View();
            }

            return RedirectToAction("Index", "porfile");
        }

    }
}

instagram/instagram/Views/Post/Create.cshtml
@model instagram.Models.Post

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<br />
<br />
<br />
<br />

@using (Html.BeginForm("Create", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo" class="form-control" />   
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}